'Ok Google, sur le pc XXX
'Ok Google, sur l'ordinateur XXX
' Applet IFTTT : https://ifttt.com/applets/jSNrZ4vJ-controle-de-l-ordinateur-avec-google-assitant
' Fichier GoogleHome.vbs a mettre dans : C:\GoogleHome

Set objArgs = WScript.Arguments
For I = 0 to objArgs.Count -1
a = a & " " & objArgs(I)	
Next

'inputbox a,a,a

Set WshShell = CreateObject("WScript.Shell")


Select Case a
Case " augmente le son"
WshShell.SendKeys "{" & chr(175) & " 10}"
Case " augmente le volume"
WshShell.SendKeys "{" & chr(175) & " 10}"
Case " monte le son"
WshShell.SendKeys "{" & chr(175) & " 10}"
Case " monte le son au max"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " monte le son au maximum"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " monte le volume au maximum"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " volume max"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " son au max"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " augmente le son au maximum"
WshShell.SendKeys "{" & chr(175) & " 50}"
Case " baisse le son"
WshShell.SendKeys "{" & chr(174) & " 10}"
Case " descend le son"
WshShell.SendKeys "{" & chr(174) & " 10}"
Case " descend le volume"
WshShell.SendKeys "{" & chr(174) & " 10}"
Case " descend le son au max"
WshShell.SendKeys "{" & chr(174) & " 50}"
Case " baisse le son au max"
WshShell.SendKeys "{" & chr(174) & " 50}"
Case " baisse le volume"
WshShell.SendKeys "{" & chr(174) & " 10}"
Case " baisse le volume au max"
WshShell.SendKeys "{" & chr(174) & " 50}"
Case " baisse le son au maximum"
WshShell.SendKeys "{" & chr(174) & " 50}"
Case " baisse le volume au maximum"
WshShell.SendKeys "{" & chr(174) & " 50}"
Case " mute le volume"
WshShell.SendKeys chr(173)
Case " mute le son"
WshShell.SendKeys chr(173)
Case " muet"
WshShell.SendKeys chr(173)
Case " le son a 0"
WshShell.SendKeys chr(173)
Case " coupe le son"
WshShell.SendKeys chr(173)
Case " coupe le volume"
WshShell.SendKeys chr(173)
Case " coupe l'audio"
WshShell.SendKeys chr(173)
Case " remet le volume"
WshShell.SendKeys chr(173)
Case " remet le son"
WshShell.SendKeys chr(173)
Case " lance chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " ouvre chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " démarre chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " exécute chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " lance google chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " ouvre google chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " démarre google chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " exécute google chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " lance google"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " ouvre google"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " démarre google"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " exécute chrome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " lorsque Rome"
WshShell.Run """C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"""
Case " fait pause"
WshShell.SendKeys " "
Case " met pause"
WshShell.SendKeys " "
Case " fais une pause"
WshShell.SendKeys " "
Case " met en pause"
WshShell.SendKeys " "
Case " mais en pause"
WshShell.SendKeys " "
Case " fait pause"
WshShell.SendKeys " "
Case " fait stop"
WshShell.SendKeys " "
Case " stop"
WshShell.SendKeys " "
Case " pause"
WshShell.SendKeys " "
Case " relance"
WshShell.SendKeys " "
Case " enlève la pause"
WshShell.SendKeys " "
Case " met une pause"
WshShell.SendKeys " "
Case " lance"
WshShell.SendKeys " "
Case " lecture"
WshShell.SendKeys " "
Case " lance lecture"
WshShell.SendKeys " "
Case " lance la lecture"
WshShell.SendKeys " "
Case " éteint le"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " arrête le"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " éteint le pc"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " éteint l'ordinateur"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " arrête le système"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " éteint le système"
CreateObject("Wscript.Shell").Run "CMD /C " & " shutdown /s /f"
Case " verrouille le"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " verrouille la session"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " verrouille le pc"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " verrouille l'ordinateur"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " le verrouiller"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " met en veille"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " mettre en veille"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " met le en veille"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " veille"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case " verrouillage"
WshShell.Run "rundll32.exe user32.dll,LockWorkStation"
Case Else
'Inputbox "La valeur n'existe pas","Erreur : valeur n'existe pas",a
End Select